server:
  port: 10008
spring:
  main:
    allow-bean-definition-overriding: true
  data:
    elasticsearch:
      cluster-name: 132.46.129.22:9200,132.46.129.23:9200,132.46.129.24:9200
      properties:
        xpack.security.user: elastic:elk@2019